# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  repodir: repo
  repobranch: master
  repourl:

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo repodir: $REPODIR
    [[ -z "$REPODIR" ]] && echo '$REPODIR not found' && exit 1
    echo repobranch: $REPOBRANCH
    [[ -z "$REPOBRANCH" ]] && echo '$REPOBRANCH not found' && exit 1
    echo repourl: $REPOURL
    [[ -z "$REPOURL" ]] && echo '$REPOURL not found' && exit 1
  displayName: 'Print environment'

# - powershell: |
#     Write-Host "##vso[task.setvariable variable=agent.jobstatus;]canceled"
#     Write-Host "##vso[task.complete result=Canceled;]DONE"
#   condition: and(succeeded(), or(eq(variables['repogit'], ''), eq(variables['repobranch'], '')))
#   displayName: 'Verify environment'

# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - task: DeleteFiles@1
#   inputs:
#     contents: $(repogit)
#   displayName: 'Clean target folder'

# - script: |
#     git clone --depth 1 --branch $(repobranch) $(repogit) $(repodir)
#     cd $(repodir)
#   displayName: 'Clone target repository'

# - task: Npm@1
#   inputs:
#      command: publish
#      workingDir: $(repodir)
#      publishRegistry: useExternalRegistry
#      publishEndpoint: openupm
#   displayName: 'Publish to OpenUPM'
